# Generated by Django 3.2.3 on 2021-05-20 10:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=40, null=True)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_city', models.CharField(default=None, max_length=25)),
                ('to_city', models.CharField(default=None, max_length=25)),
                ('purpose', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('lp_number', models.IntegerField(blank=True, null=True)),
                ('wheel_count', models.IntegerField(choices=[(4, 4), (6, 6), (8, 8), (10, 10)], default=None)),
                ('manufacturer', models.CharField(default=None, max_length=25)),
                ('model_name', models.CharField(default=None, max_length=25)),
                ('vehicle_price', models.IntegerField(default=0)),
                ('color', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('grey', 'Grey'), ('white', 'White'), ('black', 'Black')], default=None, max_length=25)),
                ('is_air_conditioned', models.BooleanField(default=True)),
                ('open_top', models.BooleanField(default=False)),
                ('my_bills', models.ManyToManyField(to='vehicles.Bill')),
            ],
            options={
                'ordering': ['model_name'],
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('lp_number', models.IntegerField(blank=True, null=True)),
                ('wheel_count', models.IntegerField(choices=[(4, 4), (6, 6), (8, 8), (10, 10)], default=None)),
                ('manufacturer', models.CharField(default=None, max_length=25)),
                ('model_name', models.CharField(default=None, max_length=25)),
                ('vehicle_price', models.IntegerField(default=0)),
                ('color', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('grey', 'Grey'), ('white', 'White'), ('black', 'Black')], default=None, max_length=25)),
                ('max_capacity', models.IntegerField(default=0)),
                ('services', models.ManyToManyField(to='vehicles.Service')),
                ('works_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.shippingagency')),
            ],
            options={
                'unique_together': {('max_capacity', 'works_for')},
            },
        ),
    ]
