# Generated by Django 3.2.3 on 2021-06-02 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='works_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='truck', to='vehicles.shippingagency'),
        ),
    ]
